### ISSUE TITLE
Bug - Setting new host on domain

### ISSUE THREAD

**Issue by g0r4n** [SteveHanna/Namecheap-dot-net#1]
Class - DnsApi
Method - SetHosts

Namecheap changed their api interface and one of the query parameters that was named "DnsRecordType" is now named "RecordType". That is the reason why API calls on namecheap will end up with response: "Object reference not set to an instance of an object.".

_**Solution**_
- To fix this issue, all you need to do is to change first parameter of function call (on line 31)
**_from_** : ` query.AddParameter("DnsRecordType" + (i + 1), Enum.GetName(typeof(DnsRecordType), request.HostEntries[i].RecordType));` 
 **_to_**: ` query.AddParameter("RecordType" + (i + 1), Enum.GetName(typeof(DnsRecordType), request.HostEntries[i].RecordType));`

**Comment by philipmat** [comment]
Seems that class already uses "RecordType":

https://github.com/SteveHanna/Namecheap-dot-net/blob/master/NameCheap/Dns/DnsApi.cs#L31
